### ISSUE TITLE
通信どうする？

### ISSUE THREAD

**Issue by kons-9** [kons-9/esp32_drone#1]
プロポのプロトコルが特殊でシリアルを反転させた信号形態らしい。
簡単な回路を作ってもいいけど、普通にwifiとかでも良いかなと
最近BLEせっかくやっているので使っても良いかなとも

**Comment by kons-9** [comment]
https://rikei-tawamure.com/entry/2020/03/17/120606

**Comment by kons-9** [comment]
https://github.com/qienhuang/esp32_mini_webserver_gpio/tree/master/main

**Comment by otama0328** [comment]
今uartで書かれているものをwifiでやるかどうかという解釈であっていますか？

**Comment by kons-9** [comment]
!!ごめんなさい見てなかった。wifiかbluetooth使おうかなと思っていてbluetoothでかいちゃいました

**Comment by kons-9** [comment]
@otama0328 
諸事情あって書き直すか頑張ってライブラリを入れるかになったのですが、wifiで書きたい！みたいなのあったりしますか...?

**Comment by kons-9** [comment]
https://www.farmsoft.jp/358/
この辺参考にすればとりあえずできそう。
speedをここから制御できれば良いのでこの記事のcountをspeedにして、buttonとして+10とか-10、リセットとかを用意してあげれば良い気がする！

**Comment by kons-9** [comment]
(やりたい場合ですが、とりあえずwifiで内部変数がいじれるくらいのコードができたらprください！)

ブランチは適当にfeature/webserverみたいな？
main.cppのやつ参考にして貰えばと！わからなければあとで移すのでとりあえず直書きでも！

**Comment by otama0328** [comment]
正直まだ理解しきれてないのですが、
src/webserver.cpp 
/////////////////////////////////////////////////////////////////////////////////////
#include <WiFi.h>
#include <ESPAsyncWebSrv.h>
#include <SPIFFS.h>

AsyncWebServer server(80);

const char* ssid = "xxxxxxxx";
const char* password = "xxxxxxxx";

ulong speed = 0;

// 内部変数でhtmlファイル内のSTATEの文字を変える
String processor(const String& var) {
  Serial.println(var);
  if (var == "SPEED") {
    return String(speed);
  } else {
    return String();
  }
}

void setup() {

    Serial.begin(115200);

    // SPIFFSのセットアップ
    if (!SPIFFS.begin(true)) {
      Serial.println("An Error has occurred while mounting SPIFFS");
      return;
    }

    WiFi.mode(WIFI_STA);
    WiFi.begin(ssid, password);
    if (WiFi.waitForConnectResult() != WL_CONNECTED) {
        Serial.printf("WiFi Failed!\n");
        return;
    }

    Serial.print("IP Address: ");
    Serial.println(WiFi.localIP());

    // GETリクエストに対するハンドラーを登録
    // rootにアクセスされた時のレスポンス
    server.on("/", HTTP_GET, [](AsyncWebServerRequest * request) {
      request->send(SPIFFS, "/index.html", String(), false, processor);
    });
    // style.cssにアクセスされた時のレスポンス
    server.on("/style.css", HTTP_GET, [](AsyncWebServerRequest * request) {
      request->send(SPIFFS, "/style.css", "text/css");
    });
    // プラスボタンにアクセスされた時のレスポンス
    server.on("/PLUS", HTTP_GET, [](AsyncWebServerRequest * request) {
      spped +=10;
    });
    // マイナスボタンにアクセスされた時のレスポンス
    server.on("/MINUS", HTTP_GET, [](AsyncWebServerRequest * request) {
      speed -= 10;
      request->redirect("/");
    });

    // ESP32_WebServer start
    server.begin();
    Serial.println("ESP32_WebServer start!");
}

void loop() {
  delay(1000);
}
//////////////////////////////////////////////////////////////////////////////////////////////////////
data/www/index.html (data/www/style.cssは省略)
<html>
  <head>
    <title>ESP32_WebServer</title>
    <link rel="stylesheet" type="text/css" href="style.css">
  </head>
  <body>
    <h1>ESP32_WebServer</h1>
    <p>速度変更</p>
    <p>スピード：%SPEED%</p>
    <p>
      <button type="button" onclick="location.href='PLUS'">プラス10</button>
      <button type="button" onclick="location.href='MINUS'">マイナス10</button>
    </p>
  </body>
</html>


 今はこういう状況です

**Comment by otama0328** [comment]
追記　gitのコメント機能勝手にhtmlを処理するなんて想定外でした

**Comment by kons-9** [comment]
今回はたいしてリッチなものを作らなくてよい気がするのでhtmlを直書きでもよいかも！
style.cssもindex.htmlの中に入れちゃってよいかも

**Comment by kons-9** [comment]
テザリングでつながることは確認したのであとでやってみましょう！
